name: my-pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: java-part
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: gradlew perm
      run: chmod a+x gradlew

    - name: build the project
      run: ./gradlew build
      

    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: aktham3/nana-action
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
